#!/usr/bin/env bash

### EDIT THIS TO WHEREVER YOU'RE STORING YOU DATA ###
# folder should exist before you mount it
DYNOSAM_ROOT=~/Thesis/ros2_ws/dynosam_pkg

LOCAL_DATA_FOLDER=$DYNOSAM_ROOT/datasets/
LOCAL_RESULTS_FOLDER=$DYNOSAM_ROOT/results/
LOCAL_DYNO_SAM_FOLDER=$DYNOSAM_ROOT/DynoSAM/
LOCAL_THIRD_PARTY_DYNO_SAM_FOLDER=$DYNOSAM_ROOT/extras/

bash create_container_base.sh acfr_rpg/dyno_sam_cuda dyno_sam $LOCAL_DATA_FOLDER $LOCAL_RESULTS_FOLDER $LOCAL_DYNO_SAM_FOLDER $LOCAL_THIRD_PARTY_DYNO_SAM_FOLDER
